(function(){'use strict';
const C=CivilCore,questions=C.compile(),byId=Object.fromEntries(questions.map(q=>[q.id,q]));
const MODES=[['word','① 핵심어'],['expanded','② 핵심어 확장'],['list','③ 목록 쓰기'],['sentence','④ 문장 완성'],['whole','⑤ 전체 답안'],['contrast','⑥ 혼동 구별']];
const KEY='civil-phrases-20261008-v1'+(new URLSearchParams(location.search).has('test')?'-browser-test':'');let state=C.emptyState(),storageOK=true,composing=false,timer=null,lastResult=null,activeQueue=[],queueKind='all',view='study',retryUnits=null;
const $=id=>document.getElementById(id),E=C.esc;
try{const raw=localStorage.getItem(KEY);if(raw)state=C.validateState(JSON.parse(raw));}catch(e){showNotice('저장된 기록을 읽지 못했습니다. 원래 저장값은 보존했습니다. 기록 내보내기로 백업한 뒤 확인하세요. '+e.message);storageOK=false;}
function showNotice(message){$('notice').textContent=message;$('notice').hidden=false;}
function save(){clearTimeout(timer);state.updatedAt=Date.now();if(!storageOK){$('save-status').textContent='저장 중지 · 기록 백업 필요';return;}try{localStorage.setItem(KEY,JSON.stringify(state));$('save-status').textContent='자동 저장됨 '+new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'});}catch(e){$('save-status').textContent='저장 실패 · 기록을 내보내세요';showNotice('브라우저 저장 공간을 사용할 수 없습니다. 현재 답안은 화면에 남아 있습니다. 기록을 내보내세요.');}}
function scheduleSave(){clearTimeout(timer);$('save-status').textContent=composing?'한글 입력 중 · 저장 대기':'저장 중…';timer=setTimeout(save,composing?800:250);}
function current(){return byId[state.current.qid]||questions[0];}
function contrast(){return CivilLearning.contrasts.filter(c=>c.refs.includes(current().number))[state.current.variant%Math.max(1,CivilLearning.contrasts.filter(c=>c.refs.includes(current().number)).length)]||CivilLearning.contrasts[0];}
function draftKey(){const s=state.current;return `${s.qid}:${s.mode}:${s.unit}:${s.variant}`;}
function draft(){const key=draftKey();if(!state.drafts[key])state.drafts[key]={values:{},assisted:false};return state.drafts[key];}
function exerciseTerms(u){return draft().retryTerms?.length?u.terms.filter(t=>draft().retryTerms.includes(t.id)):C.blankTerms(u,state.current.mode,state.current.variant);}
function capture(){const d=draft();let changed=false;document.querySelectorAll('#inputs [data-answer]').forEach(el=>{if(d.values[el.dataset.answer]!==el.value){changed=true;d.values[el.dataset.answer]=el.value;}});if(changed)d.editedAt=Date.now();scheduleSave();}
function selectedUnits(){const q=current(),s=state.current,ids=retryUnits||draft().retryUnits;if(ids)return q.units.filter(u=>ids.includes(u.id));if(s.mode==='word'||s.mode==='expanded'||s.mode==='sentence')return [q.units[Math.max(0,s.unit)]||q.units[0]];if(s.mode==='whole'&&s.unit>=0)return [q.units[s.unit]||q.units[0]];return q.units;}
function assist(){C.exposure(state,current().id);draft().assisted=true;capture();updateAssistance();}
function updateAssistance(){const help=C.isAssisted(state,current().id,draft());$('assistance').textContent=help?'도움 사용 풀이':'힌트·정답 미열람';}
function setView(name){if(composing)return;capture();view=name;for(const v of ['study','coverage','settings'])$(v+'-view').hidden=v!==name;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));location.hash=name;if(name==='coverage')renderCoverage();if(name==='settings')renderSettings();}
function setQuestion(id){if(composing)return;capture();state.current.qid=id;state.current.unit=state.current.mode==='whole'||state.current.mode==='list'?-1:0;state.current.variant=0;retryUnits=null;render();save();}
function renderQuestionSelect(){const p=$('progression').value;const subset=questions.filter(q=>p==='all'||q.progression===p);$('question-select').innerHTML=subset.map(q=>`<option value="${q.id}">원문 ${q.number}번 · 책 ${q.bookPages.join('–')}쪽</option>`).join('');if(subset.some(q=>q.id===state.current.qid))$('question-select').value=state.current.qid;}
function rebuildQueue(kind=queueKind){queueKind=kind;let subset=questions.filter(q=>$('mix').checked||$('progression').value==='all'||q.progression===$('progression').value);activeQueue=C.queue(state,subset,kind);if($('mix').checked)activeQueue=activeQueue.map(x=>[x,Math.random()]).sort((a,b)=>a[1]-b[1]).map(x=>x[0]);document.querySelectorAll('[data-queue]').forEach(b=>b.classList.toggle('selected',b.dataset.queue===kind));$('queue-info').textContent=`${{all:'전 범위',due:'오늘 복습',weak:'취약 문구',new:'새 문제'}[kind]} ${activeQueue.length}문항 · 아직 연습하지 않은 원문 ${C.queue(state,questions,'new').length}문항`;renderWeak();}
function textarea(key,label,value,cls=''){return `<label class="answer-label" for="a-${E(key)}">${label}</label><textarea id="a-${E(key)}" class="${cls}" data-answer="${E(key)}" spellcheck="false" autocomplete="off" placeholder="여기에 직접 써 보세요.">${E(value||'')}</textarea>`;}
function render(){
 lastResult=null;document.querySelectorAll('[data-rating]').forEach(b=>b.disabled=false);const q=current(),s=state.current,d=draft(),units=selectedUnits();
 $('source-meta').textContent=`원문 ${q.number}번 · PDF ${q.pdfPages.join('–')}쪽 / 책 ${q.bookPages.join('–')}쪽`;
 $('question').textContent=s.mode==='contrast'?contrast().question:q.question;
 $('correction-notice').hidden=!q.notes.length;$('correction-notice').textContent=q.notes.some(n=>n.hold)?'확인 보류 문구가 있습니다. 해당 구절은 암기 채점에서 제외합니다. 원문 확인에서 대조하세요.':q.notes.length?'교정·보충 메모가 있습니다. 원문과 학습본을 구별합니다.':'';
 $('modes').innerHTML=MODES.map(([id,title])=>`<button type="button" data-mode="${id}" class="${s.mode===id?'active':''}" aria-pressed="${s.mode===id}">${title}</button>`).join('');
 const allAllowed=s.mode==='whole'||s.mode==='list';$('unit-wrap').hidden=s.mode==='contrast'||s.mode==='list';$('unit-select').innerHTML=(allAllowed?'<option value="-1">전체 답안</option>':'')+q.units.map((u,i)=>`<option value="${i}">${u.table?'표':'부분'} ${i+1}/${q.units.length}</option>`).join('');$('unit-select').value=String(s.unit);
 $('variant').hidden=!['word','expanded','contrast'].includes(s.mode);$('variant').textContent=s.mode==='contrast'?'다른 비교 문제':'빈칸 위치 바꾸기';
 $('exercise-label').textContent=s.mode==='contrast'?`추가 비교 연습 · 근거 ${contrast().refs.join(', ')}번`:`${MODES.find(x=>x[0]===s.mode)[1]} · ${s.unit<0?'전체':`부분 ${s.unit+1}`}`;
 let html='';
 if(['word','expanded'].includes(s.mode)){
  $('instruction').textContent='조사·어미는 남겨 두었습니다. 빈칸에는 핵심 단어만 입력하세요.';
  for(const u of units){let end=0;const terms=exerciseTerms(u);html+=`<div class="blank-unit">`;for(const t of terms){html+=E(u.text.slice(end,t.start))+`<input data-answer="${E(t.id)}" value="${E(d.values[t.id]||'')}" aria-label="빈칸 ${terms.indexOf(t)+1}" spellcheck="false" autocomplete="off" style="width:${Math.min(230,Math.max(92,t.word.length*17+25))}px">`;end=t.end;}html+=E(u.text.slice(end))+`</div>`;}
 }else if(s.mode==='sentence'){
  $('instruction').textContent='첫 구절을 이어 문장 전체를 써 보세요. 핵심어 순서가 맞으면 어순 충족으로 채점합니다.';
  for(const u of units){const first=u.text.match(/^.{1,18}?(?:은|는|란|이란|에서|경우)/)?.[0]||u.text.slice(0,Math.min(12,u.text.length));html+=`<div class="prompt-start">${E(first)}…</div>`+textarea(u.id,'문장 완성',d.values[u.id]);}
 }else if(s.mode==='contrast'){
  $('instruction').textContent='추가 문제입니다. 원문 문항 수에 포함하지 않습니다. 각 상황의 요건·효과를 구별해 쓰세요.';
  contrast().items.forEach(([label],i)=>html+=textarea('contrast'+i,E(label),d.values['contrast'+i]));html+='<p>'+contrast().refs.map(n=>`<button type="button" data-ref="q${n}">근거 ${n}번 원문</button>`).join(' ')+'</p>';
 }else{
  $('instruction').textContent=s.mode==='list'?`학습용으로 나눈 ${units.length}개 부분의 요건·논거·결론을 직접 쓰세요. 항목의 순서는 자유롭습니다. 한 항목은 한 줄에 써 주세요.`:'문제만 보고 답안을 써 보세요. 문장 안의 핵심어 순서는 맞추고, 항목 사이에는 줄바꿈을 해 주세요.';
  html=textarea('full',s.mode==='list'?'요건·논거·예외 목록':'답안',d.values.full,'whole');
 }
 if(['sentence','whole','list'].includes(s.mode)&&CivilLearning.prompts[q.number])$('instruction').textContent='학습용 지시: '+CivilLearning.prompts[q.number]+' '+$('instruction').textContent;
 $('inputs').innerHTML=html;$('hint-area').hidden=true;$('hint-area').textContent='';$('results').hidden=true;$('results').innerHTML='';$('self-grade').hidden=true;$('record-status').textContent='';$('retry').disabled=true;updateAssistance();renderQuestionSelect();rebuildQueue();
 document.querySelectorAll('#inputs [data-answer]').forEach(el=>{el.addEventListener('input',()=>{capture();if(lastResult){lastResult=null;$('self-grade').hidden=true;$('results').hidden=true;$('retry').disabled=true;}});el.addEventListener('compositionstart',()=>{composing=true;});el.addEventListener('compositionend',()=>{composing=false;capture();});});
}
function highlight(unit,result){let at=0,html='';for(const t of unit.terms){const bad=result&&[...result.missing,...result.outOfOrder,...result.contradictions].some(x=>x.id===t.id);html+=E(unit.text.slice(at,t.start))+`<mark class="${bad?'bad':result?'good':''}">${E(t.word)}</mark>`;at=t.end;}return html+E(unit.text.slice(at));}
function comparison(units,result){const d=draft(),mode=state.current.mode;return units.map((u,i)=>{const r=result?.details.find(x=>x.unitId===u.id);let user=mode==='whole'||mode==='list'?d.values.full||'':d.values[u.id]||'';if(['word','expanded'].includes(mode)){let end=0;user='';for(const t of C.blankTerms(u,mode,state.current.variant)){user+=u.text.slice(end,t.start)+(d.values[t.id]||'［미입력］');end=t.end;}user+=u.text.slice(end);}return `<section class="result-unit"><h3>학습용 부분 ${i+1}${u.table?' · 원문 표':''}</h3>${r?`<p class="error-line">${r.missing.length?'누락: '+r.missing.map(t=>E(t.word)).join(' · '):''}${r.outOfOrder.length?' / 순서 차이: '+r.outOfOrder.map(t=>E(t.word)).join(' · '):''}${r.contradictions.length?' / 부정·효과 대조: '+r.contradictions.map(t=>E(t.word)).join(' · '):''}${r.wrongReferences.length?' / 조문 차이: '+r.wrongReferences.map(E).join(' · '):''}</p>`:''}<div class="compare"><div><strong>내가 쓴 답안</strong><div class="answer-text">${E(user||'(미입력)')}</div></div><div><strong>기준 답안 · 핵심어 표시</strong><div class="answer-text">${highlight(u,r)}</div></div></div></section>`;}).join('');}
function calculate(){const d=draft(),s=state.current,units=selectedUnits();
 if(['word','expanded'].includes(s.mode)){const details=units.map(u=>{const terms=exerciseTerms(u),hits=[],missing=[];terms.forEach(t=>(C.gradeBlank(d.values[t.id]||'',t).pass?hits:missing).push(t));return {unitId:u.id,hits,missing,outOfOrder:[],contradictions:[],wrongReferences:[],pass:missing.length===0};});const total=details.reduce((sum,r)=>sum+r.hits.length+r.missing.length,0),score=total?Math.round(100*details.reduce((sum,r)=>sum+r.hits.length,0)/total):0;return {details,coverage:score,phraseScore:score,pass:total>0&&details.every(r=>r.pass),manual:false};}
 if(s.mode==='contrast'){const units=contrast().items.map(([label,terms],i)=>{const bare=terms.flatMap(C.bareWords);let at=0;return {id:'contrast'+i,text:bare.join(' '),terms:bare.map((word,j)=>{const term={id:current().id+'.'+contrast().id+'.t'+i+'.'+j,word,start:at,end:at+word.length};at+=word.length+1;return term;})};});return C.gradeUnits(d.values,units);}
 if(s.mode==='sentence')return C.gradeUnits(d.values,units);
 return C.gradeWhole(d.values.full||'',units);
}
function grade(){if(composing){showNotice('한글 입력을 먼저 완료한 뒤 채점해 주세요.');return;}capture();lastResult=calculate();const r=lastResult,s=state.current;
 const blank=['word','expanded'].includes(s.mode),label=r.pass?(blank?'핵심어 정답':'핵심어 순서 충족'):'다시 연습할 부분이 있습니다';
 $('results').hidden=false;$('self-grade').hidden=false;$('retry').disabled=r.pass;
 $('results').innerHTML=`<div class="scores"><div class="score"><strong>${r.coverage}%</strong>${blank?'빈칸 정답':'필수 핵심어 포함'}</div><div class="score"><strong>${r.phraseScore}%</strong>${blank?'선정 단어 재현':'핵심어 순서 재현'}</div></div><p><span class="badge ${r.pass?'good':'bad'}">${label}</span> <span class="badge ${C.isAssisted(state,current().id,draft())?'warn':''}">${C.isAssisted(state,current().id,draft())?'도움 사용':'힌트·정답 미열람'}</span></p>${blank?'':`<p class="meta">${r.keywordOnly?'핵심어 나열도 어순 연습 점수에 반영했습니다. 문장·주체·조건이 맞는지는 직접 대조하세요.':'자동 점수는 내용·어순 대조이지 법적 정확성의 확정 판정이 아닙니다.'}</p>`}`;
 if(s.mode==='contrast'){
  $('results').innerHTML+=contrast().items.map(([label,terms],i)=>`<div class="result-unit"><strong>${E(label)}</strong><div class="compare"><div class="answer-text">${E(draft().values['contrast'+i]||'(미입력)')}</div><div class="answer-text">핵심어 배열: ${terms.map(E).join(' → ')}</div></div></div>`).join('');
 }else $('results').innerHTML+=comparison(selectedUnits(),r);
 // 採点で解答を表示する前の試行の援助状態を確定。以後の書き直しは援助付き。
 lastResult.assistedBefore=C.isAssisted(state,current().id,draft());C.exposure(state,current().id);save();
 $('record-status').textContent='기준 답안과 대조하고 기억 상태를 기록해 주세요.';
}
function rate(rating){if(!lastResult)return;const s=state.current,scope=(s.mode==='word'||s.mode==='expanded'||s.mode==='sentence'||s.mode==='whole'&&s.unit>=0)?`${s.mode}@${s.unit}`:s.mode;
 const r=C.record(state,current().id,scope,lastResult,rating,lastResult.assistedBefore);state.requeue=state.requeue.filter(x=>!(x.qid===current().id&&x.mode===scope&&lastResult.pass&&rating==='exact'));$('record-status').textContent=`기록됨 · ${lastResult.assistedBefore?'교정·도움 사용 풀이':'독립 풀이'} · 도움 없이 성공한 날짜 ${r.independentDays.length}일 · 다음 복습 ${r.interval?`${r.interval}일 뒤`:'다른 3문항 뒤'}`;save();rebuildQueue();lastResult.recorded=true;document.querySelectorAll('[data-rating]').forEach(b=>b.disabled=true);}
function next(){if(composing)return;capture();rebuildQueue();const retry=state.requeue.find(r=>C.retryReady(state,r)&&r.qid!==current().id);let id=retry?.qid;
 if(!id){const at=activeQueue.indexOf(current().id);id=activeQueue[(at+1)%Math.max(1,activeQueue.length)];}
 if(!id){showNotice('이 목록에서 지금 풀 문제는 없습니다. 새 문제 또는 전 범위 점검을 선택하세요.');return;}
 if(retry){const m=retry.mode.split('@');state.current.mode=m[0];}
 setQuestion(id);
}
function retry(onlyWrong){if(composing)return;capture();assist();const q=current(),prior=lastResult,oldMode=state.current.mode;
 const wrong=onlyWrong&&prior?prior.details.filter(r=>!r.pass):[],termIds=wrong.flatMap(r=>[...r.missing,...r.outOfOrder,...r.contradictions].map(t=>t.id));
 retryUnits=onlyWrong&&wrong.length&&oldMode!=='contrast'?wrong.map(r=>r.unitId):null;
 state.current.mode=oldMode==='contrast'?'contrast':onlyWrong&&termIds.length?'word':'sentence';state.current.unit=retryUnits?Math.max(0,q.units.findIndex(u=>u.id===retryUnits[0])):Math.max(0,state.current.unit);state.current.variant++;const d=draft();d.assisted=true;if(state.current.mode==='word')d.retryTerms=termIds;
 if(retryUnits)d.retryUnits=retryUnits;render();save();document.querySelector('#inputs [data-answer]')?.focus();}
function sourceOpen(target){assist();const q=typeof target==='string'?(byId[target]||current()):current();const table=q.table?`<h3>${E(q.table.title||'원문 표')}</h3><div class="table-scroll"><table><thead><tr>${q.table.headers.map(x=>`<th>${E(x)}</th>`).join('')}</tr></thead><tbody>${q.table.rows.map(row=>`<tr>${row.map(x=>`<td>${E(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'';
 $('source-content').innerHTML=`<p class="meta">원문 ${q.number}번 · ${E(q.chapter)} · ${E(q.reference)}${q.mnemonic?' · 두문자 ['+E(q.mnemonic)+']':''}</p><h3>${E(q.question)}</h3><h3>원문 전사 · 교정 전</h3><div class="original-text">${E(q.originalAnswer)}</div>${table}<h3>교정·확인 보류</h3>${q.notes.length?q.notes.map(note=>`<p class="source-warning"><strong>${note.status==='verified'?'공식 확인':'미확인·주의'}</strong> · ${E(note.note)} ${note.url?`<a href="${E(note.url)}" target="_blank" rel="noopener">${E(note.authority)}</a>`:''}</p>`).join(''):'<p>개별 교정 없음. 최신 법리 전수 확인을 뜻하지 않습니다.</p>'}<h3>학습본 · 출제 보류 부분 제외</h3><div class="original-text">${E(q.studyAnswer)}</div><h3>개인용 원문 페이지</h3><p class="meta">스캔에서 직접 대조하세요. 공개 배포판에는 원문 PDF·이미지를 넣지 마세요.</p>${q.pdfPages.map(p=>`<p><a class="private-pdf" href="private-sources/original.pdf#page=${p}" target="_blank">PDF ${p}쪽 / 책 ${p+149}쪽 열기</a></p><img class="page-image" src="private-sources/page-${String(p).padStart(2,'0')}.png" alt="PDF ${p}쪽 원문 스캔" loading="lazy">`).join('')}<label class="file-button">내 PDF 선택<input id="local-pdf" type="file" accept="application/pdf"></label><div id="local-source"></div>`;
 $('source-content').querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;const p=document.createElement('p');p.className='meta';p.textContent='이 배포판에는 개인용 원문 이미지가 없습니다. 아래에서 내 PDF를 선택하세요.';img.after(p);}));
 $('local-pdf').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const url=URL.createObjectURL(f);$('local-source').innerHTML=`<a href="${url}#page=${q.pdfPages[0]}" target="_blank">선택한 PDF ${q.pdfPages[0]}쪽 열기</a>`;const close=()=>{URL.revokeObjectURL(url);$('source-dialog').removeEventListener('close',close);};$('source-dialog').addEventListener('close',close);});$('source-dialog').showModal();}
function renderCoverage(){const seen=questions.filter(q=>Object.keys(state.records).some(k=>k.startsWith(q.id+':'))).length;$('coverage-summary').innerHTML=`<p><span class="badge">원문 ${questions.length}/44 수록</span> <span class="badge">연습 기록 ${seen}/44</span> <span class="badge">미연습 ${44-seen}문항</span> <span class="badge">11·32번 페이지 연결 / 14·22번 표 수록</span></p>`;
 $('coverage-table').innerHTML=`<thead><tr><th>원문</th><th>진도·출처</th>${MODES.slice(0,5).map(m=>`<th>${E(m[1])}</th>`).join('')}</tr></thead><tbody>${questions.map(q=>`<tr><td><button data-jump="${q.id}">${q.number}번 연습</button></td><td>${E(CivilLearning.progressions.find(p=>p.id===q.progression).name)}<br>PDF ${q.pdfPages.join('–')} / 책 ${q.bookPages.join('–')}</td>${MODES.slice(0,5).map(([m])=>`<td>${stageSummary(q,m)}</td>`).join('')}</tr>`).join('')}</tbody>`;}
function stageSummary(q,m){const entries=Object.entries(state.records).filter(([k])=>k===q.id+':'+m||k.startsWith(q.id+':'+m+'@')),full=state.records[q.id+':'+m];if(!entries.length)return '미연습';const n=entries.reduce((a,[,r])=>a+r.attempts,0);if(m==='whole')return `연습 ${n}회<br>${full?'전체 독립 성공 '+full.independentDays.length+'일':'전체 미연습'}<br>부분 연습 ${entries.filter(([k])=>k.includes('@')).length}/${q.units.length}`;return `연습 ${n}회<br>${['word','expanded','sentence'].includes(m)?'부분별 최대 ':''}독립 성공 ${Math.max(...entries.map(([,r])=>r.independentDays.length))}일${['word','expanded','sentence'].includes(m)?'<br>연습 부분 '+entries.length+'/'+q.units.length:''}`;}
function renderWeak(){$('weak-list').innerHTML=Object.values(state.terms).filter(t=>t.misses>0).sort((a,b)=>b.misses-a.misses).slice(0,5).map(t=>`<button data-weak="${E(t.qid)}" data-term="${E(t.word)}">${E(t.qid.slice(1))}번 취약 문구 · 누락 ${t.misses}회</button>`).join('');}
function renderSettings(){if(!$('weak-details'))$('settings-view').insertAdjacentHTML('beforeend','<details class="card"><summary>취약 문구별 누락·독립 성공 기록</summary><div id="weak-details"></div></details>');$('weak-details').innerHTML=Object.values(state.terms).filter(t=>t.misses>0).sort((a,b)=>b.misses-a.misses).map(t=>`<p>${E(t.qid.slice(1))}번 · <strong>${E(t.word)}</strong> · 누락 ${t.misses}/${t.seen}회 · 독립 성공 ${t.independentDays.length}일</p>`).join('')||'<p>아직 취약 문구 기록이 없습니다.</p>';$('storage-details').textContent=`기록 ${state.history.length}회 · 작성 칸 ${Object.keys(state.drafts).length}개 · 버전 ${CivilSource.version}`;$('aliases').innerHTML=Object.entries(CivilLearning.aliases).map(([k,v])=>`<p>${E(k)} = ${v.map(E).join(' / ')}</p>`).join('');$('correction-list').innerHTML=CivilCorrections.map(n=>`<details><summary>${n.question}번 · ${n.status==='verified'?'확인된 교정·보충':'미확인·주의'}</summary><p>${E(n.note)} ${n.url?`<a href="${E(n.url)}" target="_blank" rel="noopener">공식 근거</a>`:''}</p></details>`).join('');}
function exportRecords(){capture();const raw=storageOK?JSON.stringify(state,null,2):localStorage.getItem(KEY)||JSON.stringify(state,null,2);const blob=new Blob([raw],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='민사소송법-학습기록-'+C.dayKey()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function importRecords(file){if(!file)return;return file.text().then(text=>{const incoming=C.validateState(JSON.parse(text));if(!confirm('현재 기록을 가져온 기록으로 바꿀까요? 먼저 내보내기로 백업하는 것을 권장합니다.'))return;state=incoming;storageOK=true;retryUnits=null;$('progression').value=current().progression;save();render();renderSettings();showNotice('답안과 학습 기록을 가져왔습니다.');}).catch(e=>showNotice('가져오기 실패: '+e.message));}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();setView('study');});
document.addEventListener('click',e=>{const ref=e.target.closest('[data-ref]');if(ref)sourceOpen(ref.dataset.ref);});
document.querySelectorAll('[data-queue]').forEach(b=>b.addEventListener('click',()=>{capture();rebuildQueue(b.dataset.queue);if(activeQueue.length)setQuestion(activeQueue[0]);else showNotice('해당 목록은 비어 있습니다. 새 문제 또는 전 범위 점검을 이용하세요.');}));
document.addEventListener('click',e=>{const mode=e.target.closest('[data-mode]');if(mode&&!composing){capture();state.current.mode=mode.dataset.mode;state.current.unit=['whole','list'].includes(mode.dataset.mode)?-1:Math.max(0,state.current.unit);retryUnits=null;render();save();}const jump=e.target.closest('[data-jump]');if(jump){setView('study');$('progression').value=byId[jump.dataset.jump].progression;setQuestion(jump.dataset.jump);}const weak=e.target.closest('[data-weak]');if(weak){capture();state.current.mode='word';setQuestion(weak.dataset.weak);const q=current(),i=q.units.findIndex(u=>u.terms.some(t=>t.word===weak.dataset.term));state.current.unit=Math.max(0,i);render();save();}const rating=e.target.closest('[data-rating]');if(rating&&!rating.disabled)rate(rating.dataset.rating);});
 $('progression').innerHTML='<option value="all">전체 진도</option>'+CivilLearning.progressions.map(p=>`<option value="${p.id}">${E(p.name)}</option>`).join('');$('progression').value=current().progression;
 $('progression').addEventListener('change',()=>{renderQuestionSelect();rebuildQueue();if(!questions.filter(q=>$('progression').value==='all'||q.progression===$('progression').value).includes(current()))setQuestion($('question-select').value);});$('question-select').addEventListener('change',()=>setQuestion($('question-select').value));$('mix').addEventListener('change',()=>rebuildQueue());$('unit-select').addEventListener('change',()=>{if(composing)return;capture();state.current.unit=Number($('unit-select').value);retryUnits=null;render();save();});$('variant').addEventListener('click',()=>{if(composing)return;capture();state.current.variant++;render();save();});
 $('answer-form').addEventListener('submit',e=>{e.preventDefault();grade();});$('hint').addEventListener('click',()=>{assist();$('hint-area').hidden=false;const mnemonic=current().mnemonic;$('hint-area').textContent=mnemonic?'원문 두문자: ['+mnemonic+']':'선정 핵심어의 첫 글자: '+selectedUnits().map(u=>u.terms.map(t=>t.word[0]).join(' · ')).join(' / ');});$('reveal').addEventListener('click',()=>{assist();$('hint-area').hidden=false;$('hint-area').innerHTML=state.current.mode==='contrast'?contrast().items.map(([l,t])=>`<p>${E(l)}: ${t.map(E).join(' → ')}</p>`).join(''):selectedUnits().map(u=>`<div class="answer-text">${E(u.text)}</div>`).join('<hr>');});
 $('source-open').addEventListener('click',sourceOpen);$('source-close').addEventListener('click',()=>$('source-dialog').close());$('next').addEventListener('click',next);$('retry').addEventListener('click',()=>retry(true));$('retry-all').addEventListener('click',()=>retry(false));$('fresh').addEventListener('click',()=>{if(composing)return;capture();const help=C.isAssisted(state,current().id,{});state.current.variant++;retryUnits=null;draft().assisted=help;render();save();if(help)showNotice('새 답안 칸을 열었습니다. 정답을 본 지 10분과 다른 3문항을 모두 지나기 전까지는 교정·도움 사용 풀이입니다.');});$('resume').addEventListener('click',()=>{const latest=Object.entries(state.drafts).filter(([,d])=>Object.values(d.values).some(Boolean)).sort((a,b)=>(b[1].editedAt||0)-(a[1].editedAt||0))[0];if(latest){capture();const [qid,mode,unit,variant]=latest[0].split(':');state.current={qid,mode,unit:Number(unit),variant:Number(variant)};retryUnits=null;render();save();}else showNotice('아직 작성 중인 답안이 없습니다.');});
 $('export').addEventListener('click',exportRecords);$('import').addEventListener('change',e=>importRecords(e.target.files[0]));$('reset').addEventListener('click',()=>{if(!confirm('이 브라우저의 답안·학습기록을 모두 삭제할까요? 이 작업은 되돌릴 수 없습니다.'))return;state=C.emptyState();storageOK=true;save();render();renderSettings();});
 window.addEventListener('pagehide',()=>{capture();save();});document.addEventListener('visibilitychange',()=>{if(document.hidden){capture();save();}});window.addEventListener('storage',e=>{if(e.key!==KEY)return;try{const incoming=JSON.parse(e.newValue);if(incoming&&JSON.stringify({...incoming,updatedAt:0})===JSON.stringify({...state,updatedAt:0}))return;}catch(_){}showNotice('다른 창에서 기록이 변경되었습니다. 여러 창에서 동시에 풀지 마세요. 현재 답안을 내보낸 뒤 새로고침해 주세요.');});
 render();setView(['study','coverage','settings'].includes(location.hash.slice(1))?location.hash.slice(1):'study');save();
 window.CivilApp={questions,getState:()=>state,grade,calculate,save,setQuestion,render,importRecords};
})();
